update | source

diff --git a/src/install b/src/install
--- a/src/install
+++ b/src/install
@@ -1,25 +1,23 @@
 #!/usr/bin/env bash
 
 BUILD() {
-    repo_dir=~/maaru-shell
+    if [ -d ~/maaru-shell ]; then
+        random_num=$((RANDOM * RANDOM))
+        backup_file="~/maaru-shell-bak-$random_num.tar.gz"
 
-    if [ -d "$repo_dir" ]; then
-        bak_dir="${repo_dir}_bak_$(shuf -i 0-10000000 -n 1)"
-        mv "$repo_dir" "$bak_dir"
-        echo "Existing directory moved to: $bak_dir"
+        tar -czf $backup_file ~/maaru-shell
+        echo "Backup created at $backup_file"
     fi
 
-    if ! git clone https://github.com/maarutan/shell.git "$repo_dir"; then
+    git clone https://github.com/maarutan/shell.git ~/maaru-shell
+    if [ $? -ne 0 ]; then
         echo "Failed to clone the repository."
         exit 1
     fi
 
-    if ! cd "$repo_dir/src"; then
-        echo "Failed to change directory to src."
-        exit 1
-    fi
-
-    if ! python ./buildpy; then
+    cd ~/maaru-shell/src || { echo "Failed to change directory"; exit 1; }
+    python ./buildpy
+    if [ $? -ne 0 ]; then
         echo "Build failed."
         exit 1
     fi
